source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, UserDetailView, UserPersonalInfoChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import IndexView, FileView, FileCreateView, FileUpdateView, FileDeleteView, PrivateUserDelete

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('file/<int:pk>/', FileView.as_view(), name='file_detail'),
    path('files/create/', FileCreateView.as_view(), name='file_create'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='file_update'),
    path('file/<int:pk>/delete/', FileDeleteView.as_view(), name='file_delete'),
    path('private_user_delete/', PrivateUserDelete.as_view(), name='private_user_delete')
]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

CHOICES = (('general', 'Общий'),
            ('hidden', 'Скрытый'),
            ('private', 'Приватный'),)


class File(models.Model):
    sign = models.CharField(max_length=200, verbose_name='Подпись')
    file = models.FileField(upload_to='uploads', verbose_name='Файл')
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name='Пользователь', related_name='file_author')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    access = models.CharField(max_length=20, choices=CHOICES, default=CHOICES[0][0],
                              verbose_name='Общий доступ')
    private = models.ManyToManyField(User, null=True, blank=True, related_name='private_file')

    def __str__(self):
        return self.sign

source/webapp/forms.py
from django import forms

from webapp.models import File


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class SimpleCreateForm(forms.ModelForm):
    class Meta:
        model = File
        exclude = ['access', 'author', 'created_at']


class CreateForm(forms.ModelForm):
    class Meta:
        model = File
        exclude = ['author', 'created_at']

source/webapp/views.py
from urllib.parse import urlencode

from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import SimpleSearchForm, CreateForm, SimpleCreateForm
from webapp.models import File


class IndexView(ListView):
    model = File
    template_name = 'index.html'
    paginate_by = 10
    paginate_orphans = 1
    ordering = '-created_at'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(sign__icontains=self.search_value),
                access='general'
            )
        else:
            queryset = queryset.filter(access='general')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class FileView(DetailView):
    model = File
    template_name = 'file_detail.html'

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if file.access == 'general' or file.access == 'hidden':
            return super().dispatch(request, *args, **kwargs)
        elif self.request.user == file.author or self.request.user in file.private.all():
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class FileCreateView(CreateView):
    model = File
    template_name = 'file_create.html'

    def get_form_class(self):
        if self.request.user.username:
            return CreateForm
        else:
            return SimpleCreateForm

    def form_valid(self, form):
        if self.request.user.username:
            form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:file_detail', kwargs={'pk': self.object.pk})


class FileUpdateView(UpdateView):
    model = File
    template_name = 'file_update.html'
    context_object_name = 'file'

    def get_form_class(self):
        if self.request.user.username:
            return CreateForm
        else:
            return SimpleCreateForm

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author or self.request.user.has_perm('webapp.change_file'):
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('accounts:login')

    def get_success_url(self):
        return reverse('webapp:file_detail', kwargs={'pk': self.object.pk})


class FileDeleteView(DeleteView):
    model = File
    template_name = 'file_delete.html'
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'file'

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author or self.request.user.has_perm('webapp.change_file'):
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('accounts:login')


class PrivateUserDelete(View):
    def post(self, request):
        file = File.objects.get(pk=int(request.POST['file_id']))
        user = User.objects.get(id=int(request.POST['user_id']))
        file.private.remove(user)
        return JsonResponse({'status':'200'})

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
{#            {% if perms.webapp.add_product %}#}
                <li class="nav-item"><a href="{% url 'webapp:file_create' %}" class="nav-link">Добавить файл</a></li>
{#            {% endif %}#}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:detail' request.user.pk %}" class="nav-link">
                    Привет, {{ request.user.username }}!
                </a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'accounts:create' %}" class="nav-link">Регистрация</a></li>
                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/file_create.html
{% extends 'base.html' %}
{% block title %}Добавить файл{% endblock %}
{% block content %}
    <h1 class="text-center">Создать файл</h1>
    <form action="{% url "webapp:file_create" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/file_delete.html
{% extends 'base.html' %}
{% block title %}Обновить товар{% endblock %}
{% block content %}
    <h3 class="text-center">Вы хотите удалить {{ file.sign }} ?</h3>
    <form class="text-center" action="{% url "webapp:file_delete" file.pk %}"
          method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="ОК" class="btn btn-danger">
        <a href="{% url 'webapp:index' %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/file_detail.html
{% extends 'base.html' %}
{% block title %}{{ file.sign }}{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>{{ file.sign }}</h1>
        {% if file.author %}
            <p class="card-text">created by <a href="">{{ file.author }}</a> at {{ file.created_at }}</p>
        {% else %}
            <p class="card-text">created by Аноним at {{ file.created_at }}</p>
        {% endif %}
        <p><a href="{{ file.file.url }}" class="btn btn-primary">Скачать</a></p>
        {% if user == file.author or request.user.has_perm.webapp.change_file%}
            <p><a href="{% url "webapp:file_update" file.pk %}" class="btn btn-secondary">Изменить</a></p>
        {% endif %}
        {% if user == file.author or request.user.has_perm.webapp.delete_file%}
            <p><a href="{% url "webapp:file_delete" file.pk %}" class="btn btn-danger">Удалить</a></p>
        {% endif %}
        <h2>Приватные пользователи:</h2>
        {% for user in file.private.all %}
            <p id="private_user_{{ user.pk }}"><strong>{{ user.username }}</strong> <a onclick="deletePrivateUser(event, {{ file.pk }}, {{ user.pk }})" class="btn btn-danger">Удалить</a></p>
        {% endfor %}
    </div>

    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        function deletePrivateUser(event, file_id, user_id) {
            event.preventDefault();
                let csrftoken = getCookie('csrftoken');
                let data = {
                    file_id: file_id,
                    user_id: user_id
                };
                $.ajax({
                            method: 'POST',
                            url: '/private_user_delete/',
                            data: data,
                            dataType: 'json',
                            headers: {
                                "X-CSRFToken": csrftoken
                            },
                            success: function () {
                                var elem = $(`#private_user_${user_id}`);
                                elem.remove();
                            }
                })
        }
    </script>
{% endblock %}

source/webapp/templates/file_update.html
{% extends 'base.html' %}
{% block title %}Обновить товар{% endblock %}
{% block content %}
    <h1 class="text-center">Обновить файл</h1>
    <form action="{% url "webapp:file_update" file.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Обновить" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Файлы{% endblock %}
{% block content %}
    <h1 class="text-center">Файлы</h1>
    {% include 'partial/simple_search.html' %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="row">
        {% for file in file_list %}
            <div class="col col-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'webapp:file_detail' file.pk %}">{{ file.sign }}</a></h5>
                        {% if file.author %}
                            <p class="card-text">created by <a href="">{{ file.author }}</a> at {{ file.created_at }}</p>
                        {% else %}
                            <p class="card-text">created by Аноним at {{ file.created_at }}</p>
                        {% endif %}
                        <a href="{{ file.file.url }}" class="btn btn-primary">Скачать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}